DELETE FROM ref_nationality;
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Afghanistan','Afghanistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Albania','Albanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Antarctica','Antarctique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Algeria','Algérie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('American Samoa','Samoa Américaines',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Andorra','Andorre',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Angola','Angola',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Antigua and Barbuda','Antigua-et-Barbuda',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Azerbaijan','Azerbaïdjan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Argentina','Argentine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Australia','Australie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Austria','Autriche',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bahamas','Bahamas',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bahrain','Bahreïn',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bangladesh','Bangladesh',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Armenia','Arménie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Barbados','Barbade',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Belgium','Belgique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bermuda','Bermudes',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bhutan','Bhoutan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bolivia','Bolivie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bosnia and Herzegovina','Bosnie-Herzégovine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Botswana','Botswana',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bouvet Island','Île Bouvet',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Brazil','Brésil',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Belize','Belize',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('British Indian Ocean Territory','Territoire Britannique de l'Océan Indien',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Solomon Islands','Îles Salomon',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('British Virgin Islands','Îles Vierges Britanniques',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Brunei Darussalam','Brunéi Darussalam',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Bulgaria','Bulgarie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Myanmar','Myanmar',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Burundi','Burundi',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Belarus','Bélarus',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cambodia','Cambodge',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cameroon','Cameroun',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Canada','Canada',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cape Verde','Cap-vert',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cayman Islands','Îles Caïmanes',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Central African','République Centrafricaine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Sri Lanka','Sri Lanka',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Chad','Tchad',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Chile','Chili',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('China','Chine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Taiwan','Taïwan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Christmas Island','Île Christmas',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cocos (Keeling) Islands','Îles Cocos (Keeling)',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Colombia','Colombie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Comoros','Comores',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mayotte','Mayotte',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Republic of the Congo','République du Congo',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('The Democratic Republic Of The Congo','République Démocratique du Congo',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cook Islands','Îles Cook',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Costa Rica','Costa Rica',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Croatia','Croatie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cuba','Cuba',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Cyprus','Chypre',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Czech Republic','République Tchèque',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Benin','Bénin',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Denmark','Danemark',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Dominica','Dominique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Dominican Republic','République Dominicaine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Ecuador','Équateur',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('El Salvador','El Salvador',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Equatorial Guinea','Guinée Équatoriale',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Ethiopia','Éthiopie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Eritrea','Érythrée',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Estonia','Estonie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Faroe Islands','Îles Féroé',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Falkland Islands','Îles (malvinas) Falkland',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('South Georgia and the South Sandwich Islands','Géorgie du Sud et les Îles Sandwich du Sud',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Fiji','Fidji',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Finland','Finlande',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Åland Islands','Îles Åland',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('France','France',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('French Guiana','Guyane Française',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('French Polynesia','Polynésie Française',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('French Southern Territories','Terres Australes Françaises',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Djibouti','Djibouti',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Gabon','Gabon',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Georgia','Géorgie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Gambia','Gambie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Occupied Palestinian Territory','Territoire Palestinien Occupé',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Germany','Allemagne',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Ghana','Ghana',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Gibraltar','Gibraltar',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Kiribati','Kiribati',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Greece','Grèce',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Greenland','Groenland',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Grenada','Grenade',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guadeloupe','Guadeloupe',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guam','Guam',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guatemala','Guatemala',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guinea','Guinée',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guyana','Guyana',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Haiti','Haïti',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Heard Island and McDonald Islands','Îles Heard et Mcdonald',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Vatican City State','Saint-Siège (état de la Cité du Vatican)',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Honduras','Honduras',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Hong Kong','Hong-Kong',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Hungary','Hongrie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Iceland','Islande',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('India','Inde',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Indonesia','Indonésie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Islamic Republic of Iran','République Islamique d'Iran',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Iraq','Iraq',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Ireland','Irlande',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Israel','Israël',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Italy','Italie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Côte d'Ivoire','Côte d'Ivoire',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Jamaica','Jamaïque',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Japan','Japon',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Kazakhstan','Kazakhstan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Jordan','Jordanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Kenya','Kenya',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Democratic People's Republic of Korea','République Populaire Démocratique de Corée',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Republic of Korea','République de Corée',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Kuwait','Koweït',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Kyrgyzstan','Kirghizistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Lao People's Democratic Republic','République Démocratique Populaire Lao',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Lebanon','Liban',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Lesotho','Lesotho',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Latvia','Lettonie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Liberia','Libéria',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Libyan Arab Jamahiriya','Jamahiriya Arabe Libyenne',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Liechtenstein','Liechtenstein',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Lithuania','Lituanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Luxembourg','Luxembourg',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Macao','Macao',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Madagascar','Madagascar',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Malawi','Malawi',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Malaysia','Malaisie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Maldives','Maldives',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mali','Mali',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Malta','Malte',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Martinique','Martinique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mauritania','Mauritanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mauritius','Maurice',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mexico','Mexique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Monaco','Monaco',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mongolia','Mongolie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Republic of Moldova','République de Moldova',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Montserrat','Montserrat',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Morocco','Maroc',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Mozambique','Mozambique',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Oman','Oman',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Namibia','Namibie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Nauru','Nauru',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Nepal','Népal',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Netherlands','Pays-Bas',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Netherlands Antilles','Antilles Néerlandaises',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Aruba','Aruba',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('New Caledonia','Nouvelle-Calédonie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Vanuatu','Vanuatu',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('New Zealand','Nouvelle-Zélande',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Nicaragua','Nicaragua',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Niger','Niger',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Nigeria','Nigéria',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Niue','Niué',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Norfolk Island','Île Norfolk',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Norway','Norvège',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Northern Mariana Islands','Îles Mariannes du Nord',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('United States Minor Outlying Islands','Îles Mineures Éloignées des États-Unis',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Federated States of Micronesia','États Fédérés de Micronésie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Marshall Islands','Îles Marshall',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Palau','Palaos',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Pakistan','Pakistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Panama','Panama',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Papua New Guinea','Papouasie-Nouvelle-Guinée',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Paraguay','Paraguay',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Peru','Pérou',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Philippines','Philippines',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Pitcairn','Pitcairn',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Poland','Pologne',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Portugal','Portugal',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Guinea-Bissau','Guinée-Bissau',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Timor-Leste','Timor-Leste',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Puerto Rico','Porto Rico',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Qatar','Qatar',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Réunion','Réunion',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Romania','Roumanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Russian Federation','Fédération de Russie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Rwanda','Rwanda',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saint Helena','Sainte-Hélène',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saint Kitts and Nevis','Saint-Kitts-et-Nevis',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Anguilla','Anguilla',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saint Lucia','Sainte-Lucie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saint-Pierre and Miquelon','Saint-Pierre-et-Miquelon',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saint Vincent and the Grenadines','Saint-Vincent-et-les Grenadines',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('San Marino','Saint-Marin',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Sao Tome and Principe','Sao Tomé-et-Principe',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Saudi Arabia','Arabie Saoudite',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Senegal','Sénégal',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Seychelles','Seychelles',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Sierra Leone','Sierra Leone',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Singapore','Singapour',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Slovakia','Slovaquie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Vietnam','Viet Nam',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Slovenia','Slovénie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Somalia','Somalie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('South Africa','Afrique du Sud',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Zimbabwe','Zimbabwe',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Spain','Espagne',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Western Sahara','Sahara Occidental',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Sudan','Soudan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Suriname','Suriname',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Svalbard and Jan Mayen','Svalbard etÎle Jan Mayen',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Swaziland','Swaziland',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Sweden','Suède',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Switzerland','Suisse',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Syrian Arab Republic','République Arabe Syrienne',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Tajikistan','Tadjikistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Thailand','Thaïlande',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Togo','Togo',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Tokelau','Tokelau',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Tonga','Tonga',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Trinidad and Tobago','Trinité-et-Tobago',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('United Arab Emirates','Émirats Arabes Unis',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Tunisia','Tunisie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Turkey','Turquie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Turkmenistan','Turkménistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Turks and Caicos Islands','Îles Turks et Caïques',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Tuvalu','Tuvalu',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Uganda','Ouganda',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Ukraine','Ukraine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('The Former Yugoslav Republic of Macedonia','L'ex-République Yougoslave de Macédoine',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Egypt','Égypte',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('United Kingdom','Royaume-Uni',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Isle of Man','Île de Man',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('United Republic Of Tanzania','République-Unie de Tanzanie',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('United States','États-Unis',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('U.S. Virgin Islands','Îles Vierges des États-Unis',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Burkina Faso','Burkina Faso',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Uruguay','Uruguay',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Uzbekistan','Ouzbékistan',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Venezuela','Venezuela',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Wallis and Futuna','Wallis et Futuna',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Samoa','Samoa',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Yemen','Yémen',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Serbia and Montenegro','Serbie-et-Monténégro',now());
INSERT INTO ref_nationality(nat_label, nat_full_name, insert_date) VALUES ('Zambia','Zambie',now());
DELETE FROM ref_nationality;
